#!/usr/bin/python3

import subprocess

update_aur = "pacaur -Syua"
update_off = "sudo pacman -Syy"
update_off2 = "sudo pacman -Syu"

def cmd(string):
    proc = subprocess.Popen(string.split())
    proc.wait()

cmd("news") #run bash script to give last news feed to determine to update or not (arch_latest_news.sh renamed to news in /usr/bin)
var = input("update? [Y/N]")
if var.lower() == "y":
    cmd(update_off)
    cmd(update_off2)
    cmd(update_aur)
else:
    print("update aborted!\n")
