#!/usr/bin/env python

import sys
import subprocess

filer =  sys.argv[1]

def cmd(c):
    proc = subprocess.Popen(c.split())
    proc.wait()

def convert(f):
    if f.endswith('.tar.bz2'):
        return 'tar xvjf'
    elif f.endswith('.tar.gz'):
        return 'tar xvzf'
    elif f.endswith('.bz2'):
        return 'bunzip2'
    elif f.endswith('.rar'):
        return 'unrar x'
    elif f.endswith('.gz'):
        return 'gunzip' 
    elif f.endswith('.tar'):
        return 'tar xvf'
    elif f.endswith('.tbz2'):
        return 'tar xvjf'
    elif f.endswith('.tgz'):
        return 'tar xvzf'
    elif f.endswith('.zip'):
        return 'unzip'
    elif f.endswith('.Z'):
        return 'uncompress'
    elif f.endswith('.7z'):
        return '7z x'

        
try:
    cmd(convert(filer) + ' ' + filer)
except TypeError:
    print('{} is not a valid file'.format(filer))
