#!/usr/bin/env python

import sys
import os
import subprocess
import argparse

def cmd(c):
    proc = subprocess.Popen(c.split())
    proc.wait()

def get_value(f):
    for k, v in EXTRACT.items():
        if f.endswith(k):
            print('Archive type: {} \nExtracting with: {}\n'.format(k,v))
            return v
            
EXTRACT = {
    '.tar.bz2': 'tar xvjf',
    '.tar.gz' : 'tar xvzf',
    '.bz2'    : 'bunzip2',
    '.rar'    : 'unrar x',
    '.gz'     : 'gunzip',
    '.tar'    : 'tar xvf',
    '.tbz2'   : 'tar xvjf',
    '.tgz'    : 'tar xvzf',
    '.zip'    : 'unzip',
    '.Z'      : 'uncompress',
    '.7z'     : '7z x'
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Extractor')
    parser.add_argument('-f','--file', required=True,
        help='extract file {}'.format([k for k in EXTRACT.keys()]))
    args = vars(parser.parse_args())

    f = args['file']
    if os.path.exists(f):
        v = get_value(f)
        if v:
            cmd(v + ' ' + f)
        else:
            raise Exception('File "{}" is not a valid archive to extract!'.format(f))
    else:
        raise Exception('File "{}" does not exist!'.format(f))
