#!/usr/bin/env python

import sys
import subprocess
import os


def helper():
    print('USAGE: ')
    print('\t{} [compressed file]'.format(sys.argv[0]))
    print('SUPPORTED FILETYPES: ')
    print('\t.tar.bz2, .tar.gz, .bz2, .rar, .gz, .tar, .tbz2, .tgz, .zip, .Z, .7z')
    print('REQUIRES: ')
    print('\tunrar, unzip, 7z, tar, bunzip2, gunzip')
    sys.exit()

filer =  sys.argv[1]

if filer in ['-h', '-help', '--help']:
    helper()

def cmd(c):
    proc = subprocess.Popen(c.split())
    proc.wait()

def convert(f):
    if f.endswith('.tar.bz2'):
        return 'tar xvjf'
    elif f.endswith('.tar.gz'):
        return 'tar xvzf'
    elif f.endswith('.bz2'):
        return 'bunzip2'
    elif f.endswith('.rar'):
        return 'unrar x'
    elif f.endswith('.gz'):
        return 'gunzip'
    elif f.endswith('.tar'):
        return 'tar xvf'
    elif f.endswith('.tbz2'):
        return 'tar xvjf'
    elif f.endswith('.tgz'):
        return 'tar xvzf'
    elif f.endswith('.zip'):
        return 'unzip'
    elif f.endswith('.Z'):
        return 'uncompress'
    elif f.endswith('.7z'):
        return '7z x'
filename = os.path.splitext(os.path.splitext(filer)[0])[0]
        
try:
    cmd(convert(filer) + ' ' + filer)
except TypeError:
    print('{} is not a valid argument [FILE, -h]'.format(filer))
